# Generated by Django 4.1.5 on 2023-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
